name: kafka-bind
version: '1.0.0'
category: Services
author: Arbor Networks
maintainer: mayhem@arbor.net
copyright: Arbor Networks
license: MIT
homepage: https://github.com/packetloop/kafka-bind#readme
extra-source-files:
- README.md
- contract/file_change_message.avsc
default-extensions:
- BangPatterns
- DefaultSignatures
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- InstanceSigs
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- OverloadedStrings
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
dependencies:
- base >=4.7 && <5
- amazonka
- amazonka-core
- amazonka-sqs
- amazonka-s3
- antiope-sqs
- avro
- bifunctors
- bytestring
- conduit
- conduit-combinators
- containers
- datadog
- directory
- either
- errors
- exceptions
- fast-logger
- hs-arbor-logger
- http-client
- hw-conduit
- hw-kafka-avro
- hw-kafka-client
- hw-kafka-conduit
- lens
- monad-control
- monad-logger
- mtl
- network
- random
- resourcet
- text
- transformers
- transformers-base
library:
  source-dirs: src
  default-extensions: []
  ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  exposed-modules:
  - App
  - App.Application
  - App.AppError
  - App.AppEnv
  - App.AppState
  - App.AWS.Env
  - App.AWS.S3
  - App.AWS.Sqs
  - App.FileChangeMessage
  - App.Kafka
  - App.Options
  - App.Options.Cmd
  - App.Options.Cmd.Help
  - App.Options.Cmd.KafkaToSqs
  - App.Options.Cmd.SqsToKafka
  - App.Options.Parser
  - App.Orphans
  - App.RunApplication
  - App.SqsMessage
  dependencies:
  - aeson
  - aeson-lens
  - conduit-extra
  - http-types
  - optparse-applicative
  - unordered-containers
  - split
  when:
  - condition: os(osx)
    cpp-options:
    - -D__attribute__(A)=
    - -D_Nullable=
    - -D_Nonnull=
executables:
  kafka-bind:
    main: Main.hs
    source-dirs: app
    default-extensions:
    - LambdaCase
    ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -threaded
    - -rtsopts
    - -O2
    dependencies:
    - kafka-bind
    - aeson
    - amazonka-sqs
    - optparse-applicative
    when:
    - condition: os(osx)
      cpp-options:
      - -D__attribute__(A)=
      - -D_Nullable=
      - -D_Nonnull=
tests:
  tests:
    main: Spec.hs
    source-dirs: tests
    ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -threaded
    dependencies:
    - kafka-bind
    - hspec
    - hedgehog
    - hw-hedgehog
    - hw-hspec-hedgehog
    - raw-strings-qq
    when:
    - condition: os(osx)
      cpp-options:
      - -D__attribute__(A)=
      - -D_Nullable=
      - -D_Nonnull=
